name: Build (Reusable)

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src/Portfolio
      
      - name: Build
        run: dotnet build ./src/Portfolio --configuration Release --no-restore
