name: Test (Reusable)

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src/Portfolio
      
      - name: Build
        run: dotnet build ./src/Portfolio --configuration Release --no-restore
      
      - name: Run unit tests (with coverage)
        run: |
          mkdir -p coverage

          for proj in $(find ./tests -name "*.Test.csproj"); do
            echo "Running tests for $proj"
            
            dotnet test $proj \
              --configuration Release \
              --no-build \
              --collect:"XPlat Code Coverage" \
              --results-directory coverage \
              --verbosity normal
          done

      - name: Install ReportGenerator
        run: |
          reportgenerator \
            -reports:"coverage/**/coverage.cobertura..xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"Cobertura;TextSummary"
      
      - name: Enforce coverage threshold
        run: |
          FILE="coverage-report/Cobertural.xml"

          if [ ! -f "$FILE"]; then
            echo "Coverage file not found"
          fi

          COVERAGE=$(xmllint --xpath "string(//coverage/@line-rate)" "$FILE")
          PERCENT=$(echo "$COVERAGE * 100" | bc -l)

          THRESHOLD=90

          RESULT=$(echo "$PERCENT < $THRESHOLD" | bc -l)

          if [ "$RESULT" -eq 1 ]; then
            echo "Coverage $PERCENT% is below threshold $THRESHOLD%"
            exit 1
          fi

          